services:
  - type: web
    name: wb-review-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn.conf.py app:app
    envVars:
      - key: WEBHOOK_ENABLED
        value: true
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_HOST
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_CLIENT_ID
        sync: false
      - key: FIREBASE_CLIENT_X509_CERT_URL
        sync: false
      - key: YOOMONEY_WALLET
        sync: false
      - key: YOOMONEY_AMOUNT
        sync: false
      - key: PORT
        value: 3000
